# server
server.port=8080
# MySQL database for dev
spring.datasource.url=jdbc:mysql://localhost:3306/notifyhub
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# jpa setting for mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# logging
logging.level.root=INFO
logging.level.com.rebellion.notifyhub=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.file.name=logs/notifyhub-dev.log