# server
server.port=8080
# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
# logging
logging.level.root=INFO
logging.level.com.rebellion.notifyhub=INFO
logging.level.org.hibernate.SQL=OFF
logging.file.name=/var/log/notifyhub/notifyhub.log
# rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}